language: rust
matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly
    include:
        - os: osx
          rust: stable

        - rust: stable
          env: FEATURES=""
        - rust: beta
          env: FEATURES=""
        - rust: nightly
          env: FEATURES=""

        - rust: stable
          env: FEATURES="--features unstable"
        - rust: beta
          env: FEATURES="--features unstable"
        - rust: nightly
          env: FEATURES="--features unstable"

sudo: false
dist: trusty

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

script:
  - cargo build $FEATURES
  - cargo test $FEATURES
